# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "997ccddccb0f00f59bacabd5f878f554"
name = "extensions-showcase-pt"
application_url = "https://shopify-extensions-showcase.trycloudflare.com"
embedded = true
extension_directories = [ "extensions/*" ]

[build]
automatically_update_urls_on_dev = true
dev_store_url = "extensions-showcase-pt.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkout_branding_settings,read_orders,read_shipping,write_checkout_branding_settings,write_delivery_customizations,write_payment_customizations,write_discounts,write_orders"

[auth]
redirect_urls = [
  "https://shopify-extensions-showcase.trycloudflare.com/auth/callback",
  "https://shopify-extensions-showcase.trycloudflare.com/auth/shopify/callback",
  "https://shopify-extensions-showcase.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
