api_version = "2025-01"

[[extensions]]
handle = "free-shipping-discount"
name = "t:name"
description = "t:description"
type = "function"

  [[extensions.targeting]]
  target = "purchase.shipping-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/free-shipping-discount/:functionId/new"
  details = "/app/free-shipping-discount/:functionId/:id"

  [extensions.input.variables]
  namespace = "$app:discount"
  key = "function-configuration"
