# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb1111dc86f43cc7b766a5a28bbf209c"
name = "DECJUBA Functions (Dev)"
handle = "decjuba-checkout-validation"
application_url = "https://worthy-holiday-cart-importance.trycloudflare.com"
embedded = true
extension_directories = [ "extensions/*" ]

[build]
automatically_update_urls_on_dev = true
dev_store_url = "decjuba-development.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkout_branding_settings,read_orders,read_shipping,write_checkout_branding_settings,write_delivery_customizations,write_payment_customizations,write_discounts,write_orders"

[auth]
redirect_urls = [
  "https://worthy-holiday-cart-importance.trycloudflare.com/auth/callback",
  "https://worthy-holiday-cart-importance.trycloudflare.com/auth/shopify/callback",
  "https://worthy-holiday-cart-importance.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
